language: go
sudo: required
dist: trusty

env:
  - rel=0.6.5.9
  - rel=0.7.0-rc3

go:
  - 1.7.5
  - tip

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - MAKEFLAGS=-j$((nproc + 1))
  - sudo apt-get update -y && sudo apt-get install -y linux-headers-$(uname -r) libblkid-dev libattr1-dev uuid-dev tree
  - curl -L https://github.com/zfsonlinux/zfs/releases/download/zfs-$rel/spl-$rel.tar.gz | tar xz -C /tmp
  - curl -L https://github.com/zfsonlinux/zfs/releases/download/zfs-$rel/zfs-$rel.tar.gz | tar xz -C /tmp
  - (cd /tmp/spl-${rel%%-*} && ./configure --prefix=/usr && make && sudo make install)
  - (cd /tmp/zfs-${rel%%-*} && ./configure --prefix=/usr && make && sudo make install)
  - sudo modprobe zfs

script:
  - go test -c
  - sudo ./go-zfs.test -test.v
  - gometalinter --disable=golint --disable=vetshadow --enable=gofmt ./... || true
  - gometalinter --disable-all --enable=golint --enable=vetshadow ./... || true

notifications:
  email: false
  slack:
    secure: "AbDJNjWyf/z+neX0HtoIUynjBcdvbhrsuyzoeaImZaanUtyo3cWNpA1M+5CApDQneaKbLqcehDBTjaLQD1fjXXtWrNvq+FgCRDJ1gvZasq13iJfYe3qtLz7n0YGHqEGzZ1lsheWtle/Sg32RlPAUZrHKWPciu7/Fg1k1ca8FsB4="
