language: go
sudo: required
dist: trusty

branches:
  only:
    - master

env:
  - rel=0.6.5.11
  - rel=0.7.3

go:
  - 1.7

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - MAKEFLAGS=-j$(($(grep -c '^processor' /proc/cpuinfo) * 2 + 1))
  - sudo apt-get update -y && sudo apt-get install -y libattr1-dev libblkid-dev linux-headers-$(uname -r) tree uuid-dev
  - cd /tmp
  - curl -L https://github.com/zfsonlinux/zfs/releases/download/zfs-$rel/spl-$rel.tar.gz | tar xz
  - curl -L https://github.com/zfsonlinux/zfs/releases/download/zfs-$rel/zfs-$rel.tar.gz | tar xz
  - (cd spl-$rel && ./configure --prefix=/usr && make && sudo make install)
  - (cd zfs-$rel && ./configure --prefix=/usr && make && sudo make install)
  - sudo modprobe zfs
  - cd $TRAVIS_BUILD_DIR

script:
  - sudo -E $(which go) test -v ./...
  - gometalinter --disable=golint --disable=vetshadow --enable=gofmt ./... || true
  - gometalinter --disable-all --enable=golint --enable=vetshadow ./... || true

notifications:
  email: false
  irc: "chat.freenode.net#cerana"
